### ISSUE TITLE
视频投屏声画不同步

### ISSUE THREAD

**Issue by os60yryz** [xfirefly/Airplay-SDK#10]
使用iPhone上的斗鱼app投屏，会出现明显的声画不同步现象。
使用bilibili app投屏，会进入视频播放模式，出现黑屏、回声等现象

**Comment by xfirefly** [comment]
win版本?

**Comment by os60yryz** [comment]
> win版本?

Win10家庭中文版

**Comment by xfirefly** [comment]
目前只做了屏幕镜像, 后续打算接 vlc 来播放视频
安卓版app 完美支持 视频模式,  bilibili app 这些都没问题

**Comment by xfirefly** [comment]
## 运行依赖
- Airplay 需要调用Apple Bonjour 广播服务, 安装zip包内的 Bonjour64.msi 或 Bonjour.msi
- 如安装后运行提示找不到 dll, 安装VC运行库 : https://aka.ms/vs/16/release/vc_redist.x86.exe

## Q & A
0. 视频投屏怎么用?
- 需要安装 [PotPlayer](https://daumpotplayer.com/download/) 或者 [VLC](https://www.videolan.org/vlc/) , 安装到C盘即可, 程序会调用其播放视频
1. 按 f 全屏后图像显示不全 ?   
-  修改 win10/设置/显示/缩放与布局 为 100%,  因请求iOS/Mac端编码1080p视频, 所以显示器最低要求为1920*1080
2. 连接黑屏 ?  
- 确认是不是防火墙禁止了exe联网
3. 杀毒软件报毒 ?
- 因程序加壳, 360或者Win杀毒会误报, 担心的话请禁止程序连互联网
4. iPhone找不到设备 win-airplay ?
- 确认安装了Apple Bonjour 服务
