### ISSUE TITLE
最大化之后图像残留，图像位置无法居中

### ISSUE THREAD

**Issue by smallprogram** [xfirefly/Airplay-SDK#11]
2K显示器，默认窗口投影后，再最大化之后，出现图像残留。

如下图：

![image](https://user-images.githubusercontent.com/6050360/73743922-9dfec580-478a-11ea-9490-47d3d7f5d17d.png)

图像位置无法居中

![image](https://user-images.githubusercontent.com/6050360/73744032-e322f780-478a-11ea-8d16-0d3ae955cbd4.png)

**Comment by xfirefly** [comment]
按 f 全屏后如果图像显示不全, 修改 win10/设置/显示/缩放与布局 为 100%

**Comment by xfirefly** [comment]
## 运行依赖
- Airplay 需要调用Apple Bonjour 广播服务, 安装zip包内的 Bonjour64.msi 或 Bonjour.msi
- 如安装后运行提示找不到 dll, 安装VC运行库 : https://aka.ms/vs/16/release/vc_redist.x86.exe

## Q & A
0. 视频投屏怎么用?
- 需要安装 [PotPlayer](https://daumpotplayer.com/download/) 或者 [VLC](https://www.videolan.org/vlc/) , 安装到C盘即可, 程序会调用其播放视频
1. 按 f 全屏后图像显示不全 ?   
-  修改 win10/设置/显示/缩放与布局 为 100%,  因请求iOS/Mac端编码1080p视频, 所以显示器最低要求为1920*1080
2. 连接黑屏 ?  
- 确认是不是防火墙禁止了exe联网
3. 杀毒软件报毒 ?
- 因程序加壳, 360或者Win杀毒会误报, 担心的话请禁止程序连互联网
4. iPhone找不到设备 win-airplay ?
- 确认安装了Apple Bonjour 服务
