### ISSUE TITLE
投送视频播放失败

### ISSUE THREAD

**Issue by oliverance** [xfirefly/Airplay-SDK#114]
现在投送Apple TV视频无效，具体表现在程序接受后调用打开VLC或PotPlayer不播放，只有报错信息（附图）。
请问有解决办法吗？(ಥ _ ಥ)
![20240810-20 26 36](https://github.com/user-attachments/assets/62a2695e-a445-47da-8ed6-503532ff8d36)

**Comment by xfirefly** [comment]
可能是服务器限制
