### ISSUE TITLE
安裝後打開不了應用

### ISSUE THREAD

**Issue by Arthur042l** [xfirefly/Airplay-SDK#116]
本來安裝好就打開來用，但是它出現了（0xc000007b）錯誤代碼，說不能打開應用程式，我已經試過重新安裝了，但是還是不行。

**Comment by xfirefly** [comment]
如运行提示无法正常启动(0xc000007b), 安装VC x86运行库 https://aka.ms/vs/17/release/vc_redist.x86.exe
