### ISSUE TITLE
How-to run automatically on windows boot or login?

### ISSUE THREAD

**Issue by BenK885** [xfirefly/Airplay-SDK#117]
How can I run the AirPlay server automatically on Windows boot or login?

**Comment by xfirefly** [comment]
https://learn.microsoft.com/en-us/answers/questions/1662339/how-can-i-launch-my-application-automatically-on-s

**Comment by BenK885** [comment]
Thank your for the link. I am aware of these methods. But I am not aware of the program / path / and parameters to start the airplay server automatically. Can you help me with providing these parameters? Maybe my question was not asked precisely enough. Sorry, for that.
