### ISSUE TITLE
无法投屏

### ISSUE THREAD

**Issue by Mion354D** [xfirefly/Airplay-SDK#12]
iPad mini 5, ios 13.3.1
Win10 1909 18363
iPad上可以看到win-airplay, 选中并显示成功连接之后电脑上依然黑屏

**Comment by shao222** [comment]
iPhone 13.3.1 也是如此, 能发现win-airplay 但一直黑屏, 知道报错.

无法投屏.

**Comment by lagrange-doggy** [comment]
设置：控制面板\系统和安全\Windows Defender 防火墙\允许的应用\更改设置\允许其他应用\找到你刚才安装的可执行文件，然后都打上对勾（两个都要打上）

**Comment by freeleefly** [comment]
Windows 10 1909 18363.592
iPhone7 plus  iOS 13.3 ，
iPad air 3 ，iPadOS 13.3
无法投屏，打开以后，“屏幕镜像”下，找不到。
已经连接在同一网络，已经装了iTunes，检查过，装了Bonjour，已经设置了防火墙，专用公用都打允许。

**Comment by xfirefly** [comment]
## 运行依赖
- Airplay 需要调用Apple Bonjour 广播服务, 安装zip包内的 Bonjour64.msi 或 Bonjour.msi
- 如安装后运行提示找不到 dll, 安装VC运行库 : https://aka.ms/vs/16/release/vc_redist.x86.exe

## Q & A
0. 视频投屏怎么用?
- 需要安装 [PotPlayer](https://daumpotplayer.com/download/) 或者 [VLC](https://www.videolan.org/vlc/) , 安装到C盘即可, 程序会调用其播放视频
1. 按 f 全屏后图像显示不全 ?   
-  修改 win10/设置/显示/缩放与布局 为 100%,  因请求iOS/Mac端编码1080p视频, 所以显示器最低要求为1920*1080
2. 连接黑屏 ?  
- 确认是不是防火墙禁止了exe联网
3. 杀毒软件报毒 ?
- 因程序加壳, 360或者Win杀毒会误报, 担心的话请禁止程序连互联网
4. iPhone找不到设备 win-airplay ?
- 确认安装了Apple Bonjour 服务
