### ISSUE TITLE
iPhone投屏声音存在延迟，爱奇艺投屏会黑屏，另外请问窗口如何全屏显示

### ISSUE THREAD

**Issue by chenbin3625** [xfirefly/Airplay-SDK#15]

**Comment by chenbin3625** [comment]
最大化已解决 但是按F在分辨率为2560X1080下 不能上下铺满 并且出现闪退现象

**Comment by chenbin3625** [comment]
iOS12.4 iPhone XS Max

**Comment by ycphoenix** [comment]
同声音延迟，试过多个如输入设备，应该跟输入设备无关
输出是win10 1909

**Comment by xfirefly** [comment]
## 运行依赖
- Airplay 需要调用Apple Bonjour 广播服务, 安装zip包内的 Bonjour64.msi 或 Bonjour.msi
- 如安装后运行提示找不到 dll, 安装VC运行库 : https://aka.ms/vs/16/release/vc_redist.x86.exe

## Q & A
0. 视频投屏怎么用?
- 需要安装 [PotPlayer](https://daumpotplayer.com/download/) 或者 [VLC](https://www.videolan.org/vlc/) , 安装到C盘即可, 程序会调用其播放视频
1. 按 f 全屏后图像显示不全 ?   
-  修改 win10/设置/显示/缩放与布局 为 100%,  因请求iOS/Mac端编码1080p视频, 所以显示器最低要求为1920*1080
2. 连接黑屏 ?  
- 确认是不是防火墙禁止了exe联网
3. 杀毒软件报毒 ?
- 因程序加壳, 360或者Win杀毒会误报, 担心的话请禁止程序连互联网
4. iPhone找不到设备 win-airplay ?
- 确认安装了Apple Bonjour 服务
