### ISSUE TITLE
投屏有声音无画面

### ISSUE THREAD

**Issue by Mion354D** [xfirefly/Airplay-SDK#20]
iPad mini 5, ios 13.3.1
Win10 1909 18363
iPad上可以看到win-airplay, 选中并显示成功连接之后电脑上依然黑屏
有声音无画面
防火墙已放行

**Comment by xfirefly** [comment]
1, 安装最新版
2, 重启电脑试试 ??

**Comment by Mion354D** [comment]
是最新版
重启无用
