### ISSUE TITLE
Windows接收端使用AirPlay播放音乐卡顿

### ISSUE THREAD

**Issue by JasprW** [xfirefly/Airplay-SDK#28]
不投屏仅使用AirPlay播放音乐会出现严重声音卡顿，声音间断不连续，投屏时无此情况。且每次结束投屏后程序自动退出，需要重新打开

**Comment by xfirefly** [comment]
仅使用AirPlay播放音乐会出现严重声音卡顿, 这个是bug..
因某些原因, 目前是镜像结束后程序自动退出
