### ISSUE TITLE
苹果手机投屏windows10 pc上。pc上没一点反应？

### ISSUE THREAD

**Issue by micenote** [xfirefly/Airplay-SDK#29]
苹果手机投屏windows10 pc上。pc上没一点反应。
防火墙，potplayer都没问题。用手机上的腾讯视频投屏，pc上没点反应

**Comment by xfirefly** [comment]
我测试了, 没有问题, 会调用potplayer 播放, 检查exe 是否存在

		"C:\\Program Files\\DAUM\\PotPlayer\\PotPlayerMini.exe",
		"C:\\Program Files\\DAUM\\PotPlayer\\PotPlayerMini64.exe",
		"C:\\Program Files\\VideoLAN\\VLC\\vlc.exe",
		"D:\\Program Files\\DAUM\\PotPlayer\\PotPlayerMini64.exe",
		"D:\\Program Files\\DAUM\\PotPlayer\\PotPlayerMini.exe",
		"D:\\Program Files\\VideoLAN\\VLC\\vlc.exe",
		"E:\\Program Files\\DAUM\\PotPlayer\\PotPlayerMini64.exe",
		"E:\\Program Files\\DAUM\\PotPlayer\\PotPlayerMini.exe",
		"E:\\Program Files\\VideoLAN\\VLC\\vlc.exe",
