### ISSUE TITLE
Android 4.4 & IPv6

### ISSUE THREAD

**Issue by faajaudai** [xfirefly/Airplay-SDK#3]
有两个的问题反馈一下：
1、最新版好像不支持Android4.4，adb安装的时候提示“Failure [INSTALL_FAILED_OLDER_SDK]”。这个不知是因为编译打包问题还是因为使用了新的库 ？其实现在很多机顶盒都是基于4.4定制，希望最好还是可以支持4.4

2、好像不能支持IPv6？v6站点的视频无法推送播放成功。

ps，可以自定义视频宽高比这个设置真的太赞了，点赞！！

**Comment by xfirefly** [comment]
感谢反馈, 后续修复
