### ISSUE TITLE
之前可以用，但现在被Windows Defender报毒了。。

### ISSUE THREAD

**Issue by Hppppppf** [xfirefly/Airplay-SDK#35]
![QQ截图20200405160510](https://user-images.githubusercontent.com/30293977/78469840-3d264600-7757-11ea-8b52-0c14ddeffeeb.png)

**Comment by wanderseeme** [comment]
同问。。这软件里是有啥猫腻么。。

**Comment by xfirefly** [comment]
upx 压缩导致, 以后不压了
