### ISSUE TITLE
Blueberry-airplay.exe 有病毒

### ISSUE THREAD

**Issue by ewd25481** [xfirefly/Airplay-SDK#37]
杀毒软件Bitdefender测出Blueberry-Airplay.exe 有病毒 Gen:Variant.Razy.628431。

![Screenshot (55)](https://user-images.githubusercontent.com/63637479/79202857-360ed000-7e08-11ea-8627-a15020255eb8.png)

**Comment by xfirefly** [comment]
😂 因为用 npx 压缩了, 不放心可以禁止连互联网

**Comment by xfirefly** [comment]
https://www.virustotal.com/gui/file/63f465fa0b043003b344415072624c6e1e1d5c530131152bbed8a25649b8547a/detection
