### ISSUE TITLE
Why my windows defender, edge browser & google chrome complain the app is unsafe 

### ISSUE THREAD

**Issue by shuwang1** [xfirefly/Airplay-SDK#43]
A great job but

none of my windows defender, edge browser & google chrome allows me to download the app. They all block the downloading.

Why is that?

**Comment by Zerdath** [comment]
My AVG also identified the download as containing malware.  I will not be trying this program out.

**Comment by xfirefly** [comment]
Because the previous version use https://github.com/upx/upx for compression.
The new version is not compressed

https://www.virustotal.com/gui/file/75c2ac2d2a3e1739c51842b509ccbc3a501fb09e3a204c13b48e5c3948205ba3/detection
