### ISSUE TITLE
具有安全威胁的木马程序

### ISSUE THREAD

**Issue by smallprogram** [xfirefly/Airplay-SDK#44]
![image](https://user-images.githubusercontent.com/6050360/82719095-1a85c780-9cda-11ea-8b0f-e65297be7e8b.png)

**Comment by xfirefly** [comment]
Because the previous version use https://github.com/upx/upx for compression.
The new version is not compressed

https://www.virustotal.com/gui/file/75c2ac2d2a3e1739c51842b509ccbc3a501fb09e3a204c13b48e5c3948205ba3/detection
