### ISSUE TITLE
Trojan detected, DO NOT DOWNLOAD

### ISSUE THREAD

**Issue by rem0g** [xfirefly/Airplay-SDK#45]
https://www.microsoft.com/en-us/wdsi/threats/threat-search?query=Trojan:Win32/Mamson.A!rfn

**Comment by xfirefly** [comment]
Because the previous version use https://github.com/upx/upx for compression.
The new version is not compressed

https://www.virustotal.com/gui/file/75c2ac2d2a3e1739c51842b509ccbc3a501fb09e3a204c13b48e5c3948205ba3/detection
