### ISSUE TITLE
Bitdefender检测出有木马

### ISSUE THREAD

**Issue by smcdl** [xfirefly/Airplay-SDK#46]
![image](https://user-images.githubusercontent.com/4975064/83344161-bdbb8a00-a335-11ea-968a-582445d37e1f.png)

**Comment by xfirefly** [comment]
Because the previous version use https://github.com/upx/upx for compression.
The new version is not compressed

https://www.virustotal.com/gui/file/75c2ac2d2a3e1739c51842b509ccbc3a501fb09e3a204c13b48e5c3948205ba3/detection
