### ISSUE TITLE
Windows下投屏清晰度较低，颜色不正

### ISSUE THREAD

**Issue by myworksfun** [xfirefly/Airplay-SDK#47]
租新版本，win10 2004版本，投屏边缘锐化太厉害，图像清晰度差，颜色较模糊。[
![Snipaste_2020-06-03_20-03-20](https://user-images.githubusercontent.com/45185967/83634539-4c016b80-a5d5-11ea-9452-f1e26146f766.jpg)

**Comment by xfirefly** [comment]
投屏本身画质肯定没 屏幕显示的清晰, 另外也可能是由sdl 渲染视频的问题
