### ISSUE TITLE
你好，iOS手机端可以作为接受端吗？

### ISSUE THREAD

**Issue by yangbo930204** [xfirefly/Airplay-SDK#54]
从别的app的投屏功能，投屏到另一个iOS手机的上。

**Comment by yangbo930204** [comment]
已找到解决方案。

**Comment by LanceDjango** [comment]
> 已找到解决方案。

请问下你怎么解决的啊，iOS手机端可以作为接受端

**Comment by yangbo930204** [comment]
> > 已找到解决方案。
> 
> 请问下你怎么解决的啊，iOS手机端可以作为接受端

https://github.com/plutinosoft/Platinum#mediarenderertest 这个库里面有示例(MediaRendererTest)，自带支持
