### ISSUE TITLE
windows版本进行ipad投屏，在广色域显示器上色差非常严重

### ISSUE THREAD

**Issue by Meng-Xi-Bi-Tan** [xfirefly/Airplay-SDK#58]
和ipad本身的色彩差距很大，严重过饱和，不知道是否可以调用系统内设置的色彩管理文件icc来纠偏一下？
直接使用ipad typec口转hdmi到显示器则色彩正常。

**Comment by BlackMickey** [comment]
在非廣色域螢幕中有相同問題，經檢驗後確認是YUV Range錯誤的問題。錯誤的將TVrange當成PCrange處理，導致過飽和。

**Comment by xfirefly** [comment]
这个可能是sdl 渲染问题..
