### ISSUE TITLE
ubuntu receiver 的教程可以写详细一点嘛？

### ISSUE THREAD

**Issue by yaochenglouis** [xfirefly/Airplay-SDK#61]
我看了半天没看明白……

**Comment by xfirefly** [comment]
sorry, ubuntu 的教程没有写上去

**Comment by yaochenglouis** [comment]
以后要补上吗？

**Comment by linus-ha** [comment]
@xfirefly luckily you've provided a screenshot of your SDK running on Ubuntu, so we know that it seems to be possible to do. I've installed all dependencies listed, but the binary is not executable (after chmod +x) on my system. Can we expect to get further information, so to be able to test the SDK on Linux ourselves?
