### ISSUE TITLE
macos catalina 无法连接

### ISSUE THREAD

**Issue by leexsoft** [xfirefly/Airplay-SDK#62]
mac book pro, 操作系统是 catalina 10.15.7, 在同一wifi里，隔空播放能发现windows机器，但是无法连接。

windows机器为 surface pro 4.

**Comment by xfirefly** [comment]
实测没问题,  最新版big sur 也是支持的..
连不上一般是电脑防火墙问题 

![apple](https://user-images.githubusercontent.com/475290/104808967-a7126680-5824-11eb-9f57-0f259e5426f4.png)
