### ISSUE TITLE
Windows比例大小会产生画质模糊

### ISSUE THREAD

**Issue by tengfong00** [xfirefly/Airplay-SDK#65]
我使用的是Windows笔电，使用的是125%比例来放大
![image](https://user-images.githubusercontent.com/56729463/107047556-e9670c00-6802-11eb-9928-f9295203bbb0.png)

我发现使用airplay的时候会画面模糊
我尝试把比例方法调回100%并发现airplay在100%比例情况下是画面清晰的

这是125%比例
![125%zoom](https://user-images.githubusercontent.com/56729463/107048714-3697ad80-6804-11eb-9893-e5aa30c238cc.png)

![100%zoom](https://user-images.githubusercontent.com/56729463/107048137-8de94e00-6803-11eb-8170-eb3f2e3f2c96.png)
这是100%比例

我使用的是iphone se 2020

**Comment by aitsc** [comment]
不需要改缩放比例:
Blueberry-Airplay.exe→右键→属性→兼容性→更改高DPI设置→替代高DPI缩放行为→勾选
