### ISSUE TITLE
爱奇艺投屏问题，如图

### ISSUE THREAD

**Issue by alonewoo** [xfirefly/Airplay-SDK#66]
ipad 5代 14.4，腾讯视频正常

爱奇艺问题如下
![image](https://user-images.githubusercontent.com/44246977/107400704-0a9a6600-6b3d-11eb-8d13-8f4578e5b855.png)

**Comment by chena1982** [comment]
win10 20H2, iPhone12 也有这个问题。

**Comment by xfirefly** [comment]
可能爱奇艺有限制, 或者PotPlayer 不支持播放
