### ISSUE TITLE
youtube 无法投屏

### ISSUE THREAD

**Issue by ZiniuLu** [xfirefly/Airplay-SDK#67]
如图，在PotPlayer中无法对youtube视频进行投屏。系统为win10专业版(20H2)，PotPlayer版本210209(1.7.21419), ipad pro 系统版本ios14.4。

对哔哩哔哩进行投屏则一切正常。

![1](https://user-images.githubusercontent.com/34126026/107590748-3e42c200-6c09-11eb-8647-6bf340666796.JPG)

**Comment by WakakaYixixi** [comment]
我也遇到相同问题

**Comment by TianRy1337** [comment]
我也是這個問題，AppleTV+也無法投屏

**Comment by xfirefly** [comment]
需要我们的定制版本才可以
