### ISSUE TITLE
Can't find the device when Use multiple name parts 

### ISSUE THREAD

**Issue by BasilAlfattal** [xfirefly/Airplay-SDK#69]
Hi :)

I wanted to point on issue that I've faced use this SDK :

- When I name the blueberry device name with two or more parts name (like "Bill Laptop" for example) , the phone could not find the mirror app .

Other issues that I would you to consider also :
- While mirroring  , window exit button won't respond , thus I have to stop mirroring from iPhone screen .

- The app won't be minimized in the array after closing it (unlike the previous version).

I've really enjoyed using the app and hope you solve these issue I mentioned .

Thanks:)

**Comment by xfirefly** [comment]
Thank you for your feedback, I will fix it in a future version
