### ISSUE TITLE
创维e900v21e 4.4.2闪退

### ISSUE THREAD

**Issue by tenwx** [xfirefly/Airplay-SDK#7]
机顶盒型号：创维e900v21e
Android：4.4.2
Kernel：Linux localhost 3.14.29 #1 SMP PREEMPT Fri Mar 2 10:50:18 CST 2018 ARMv71 GNU/Linux
报错截图：
![image](https://user-images.githubusercontent.com/3733304/73252120-2f06f700-41f5-11ea-8022-98fc7def0cb5.png)

**Comment by xfirefly** [comment]
谢谢反馈, 这个是 mdns 的bug,  目前app 会调用安卓自带mdnsd 发布服务.

**Comment by tenwx** [comment]
谢谢，我使用build33版本还是会闪退，是不是还要等你的更新？

**Comment by faajaudai** [comment]
> 谢谢反馈, 这个是 mdns 的bug, 目前app 会调用安卓自带mdnsd 发布服务.

一样也是fc，移动魔百盒，应该是海思平台，Android4.4
乐X投屏，果X投屏，测试是可以正常运行，系统应该没有缺少什么库吧
看日志好像也是什么mdnssd在报错，
希望能够修复

`
D/dalvikvm( 9844): Trying to load lib /data/app-lib/com.blueberrytek-1/libmdnssd.so 0x419b2220
E/dalvikvm( 9844): dlopen("/data/app-lib/com.blueberrytek-1/libmdnssd.so") failed: dlopen failed: cannot locate symbol "__FD_SET_chk" referenced by "libmdnssd.so"...
W/dalvikvm( 9844): Exception Ljava/lang/UnsatisfiedLinkError; thrown while initializing Lcom/blueberrytek/jni/PlatinumJniProxy;
W/dalvikvm( 9844): threadid=28: thread exiting with uncaught exception (group=0x417c6bc0)
D/StatFs  ( 9844): getBlockCount
D/XIRI_driver( 1787): server scanning again ...
D/XIRI_driver( 1787): name file read out 13 bytes.
D/XIRI_driver( 1787): server name is [XIRI_34531283].
D/XIRI_driver( 1787): connect server[XIRI_34531283] failed.
D/XIRI_driver( 1787): now 1580748197 from 1580746428, duration 1769
E/AndroidRuntime( 9844): FATAL EXCEPTION: Thread-306
E/AndroidRuntime( 9844): Process: com.blueberrytek, PID: 9844
E/AndroidRuntime( 9844): java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__FD_SET_chk" referenced by "libmdnssd.so"...
E/AndroidRuntime( 9844):      at java.lang.Runtime.loadLibrary(Runtime.java:364)
E/AndroidRuntime( 9844):      at java.lang.System.loadLibrary(System.java:526)
E/AndroidRuntime( 9844):      at com.blueberrytek.jni.PlatinumJniProxy.<clinit>()
E/AndroidRuntime( 9844):      at com.blueberrytek.center.c.f()
E/AndroidRuntime( 9844):      at com.blueberrytek.center.c.c()
E/AndroidRuntime( 9844):      at com.blueberrytek.center.c.run()
W/ActivityManager( 2189):   Force finishing activity com.blueberrytek/.home.MainActivity
I/Process ( 9844): Sending signal. PID: 9844 SIG: 9
D/StatFs  ( 2189): restat
D/StatFs  ( 2189): getBlockCount
I/ActivityManager( 2189): Process com.blueberrytek (pid 9844) has died.
I/WindowState( 2189): WIN DEATH: Window{41c9dce0 u0 com.blueberrytek/com.blueberrytek.home.MainActivity}
D/ActivityManager( 2189): cleanUpApplicationRecordLocked -- 9844



`

**Comment by xfirefly** [comment]
后续解决中.. 目前上不了班 😂😂

**Comment by xfirefly** [comment]
已经更新, 4.4 没问题了

**Comment by tenwx** [comment]
试了下Build 40虽然不闪退了，但启动后iphone上看不到蓝莓投屏这个镜像投屏设备，是不是mdns并没有正常工作？
