### ISSUE TITLE
央视频投屏不了

### ISSUE THREAD

**Issue by cottonty** [xfirefly/Airplay-SDK#71]
地址这样的

D:\Downloads\win-airplay\http://hlsoutplaycloud-cdn.ysp.cctv.cn/98A871169A43BA93FEABC1E3B56395D94B90B6666301B855D71A74B02BFEDA3A56FF064BA2BA4F80EFE43DCD80C2A82CDCB52FE8394C000AB95830D5D6D220B3EEA1E39AE26A4B05A4160A8C24CB69AB699AAC6E9DC38BA466240D22A5FD253C3F467CB8C341DF5BD810F919DCC52E6C11586BBB6C1454983DB3156FEA6CF7C6531B6B32953434C1E3B3B034F5BB50D95E5977F0B74EB421520E8BA49D39305F/m000082kbuv.gLqk20004.ts.m3u8?ver=4&sdtfrom=v3021 --play-and-exit

**Comment by xfirefly** [comment]
和协议无关, 需要播放器支持才行
