### ISSUE TITLE
只投音频会闪退

### ISSUE THREAD

**Issue by a-little-cat** [xfirefly/Airplay-SDK#72]
操作:
ios设备向windows设备投射音频
现象:
windows会有2秒左右的声音放出,然后停止,程序不崩溃
ios设备自动切回本机继续播放,不能再次搜索到windows设备

版本:
ios:14.4.2
win:19042.844
投屏版本:刚刚下载最新版

**Comment by a-little-cat** [comment]
投射屏幕镜像是正常的..

**Comment by xfirefly** [comment]
已知问题, 暂不处理, 使用的人太少, 免费软件, 请理解
