### ISSUE TITLE
windows上安装了receiver，iphone的屏幕镜像为什么收不到呢

### ISSUE THREAD

**Issue by zzzzhongzhen** [xfirefly/Airplay-SDK#75]
windows上安装了receiver，iphone的屏幕镜像为什么收不到呢

**Comment by xfirefly** [comment]
http://www.deeprd.com/docs/

**Comment by ShannonHung** [comment]
我是使用windows10 我有先去 > 防火牆與網路保護 / 允需應用程式通過防火牆 
然後把所有airplay, blueberry相關的.exe都打開。我後來打開之後終於看到屏幕鏡像有東西了
