### ISSUE TITLE
您好，有没有可能增加隔空播放的功能？

### ISSUE THREAD

**Issue by waynehoo** [xfirefly/Airplay-SDK#77]
您好，有没有可能增加隔空播放的功能。
我目前使用的情况是用【屏幕镜像】连接您开发的【蓝莓】，音乐或者视频都是投屏的形式，目前很大程度地满足我的需求。今天发现【屏幕镜像】连接上后，听歌的时候【隔空播放】功能是连接到【蓝莓】的。后面我尝试断开屏幕镜像，直接使用隔空播放是找不到连接不到蓝莓的。如果能连接上是否能仅播放音频呢？这样听音乐或者播客的时候可以投到电脑通过自己的音响设备播放，实现了隔空播放到非苹果产品的音响。不知道技术上能不能实现，或者您认为是否有这个必要。
最后，谢谢您开发的这么好的产品！
![微信截图_20210612145144](https://user-images.githubusercontent.com/40262229/121768055-a5a85880-cb8e-11eb-893a-14d60c53b836.png)

**Comment by xfirefly** [comment]
技术上可以实现, 但不如买一个支持 airplay的音响, 现在价格也不贵
