### ISSUE TITLE
Where is the code?

### ISSUE THREAD

**Issue by MikeCodesDotNET** [xfirefly/Airplay-SDK#79]
I can't find any code for this project, just binary downloads. GitHub is meant for sharing code, and not for providing you with free blob storage. Can you let me know where you've published the source code?

**Comment by xfirefly** [comment]
sorry, not open-source

**Comment by MikeCodesDotNET** [comment]
> sorry, not open-source

Then why are you hosting it on here?

**Comment by computersandstuff** [comment]
> > sorry, not open-source
> 
> Then why are you hosting it on here?

Yes, GitHub is made for open source projects. I'm curious why you chose this platform?
