### ISSUE TITLE
windows 高分屏显示错误

### ISSUE THREAD

**Issue by Markghz** [xfirefly/Airplay-SDK#8]
在windows平台，高分屏笔记本作为接收端，显示不正常

**Comment by xfirefly** [comment]
4k显示器已经在路上, 会修复的

**Comment by MisterGlasses** [comment]
![批注 2020-02-03 232401](https://user-images.githubusercontent.com/27768847/73665585-4e61c080-46dc-11ea-88f1-98a4f0619f09.png)
是这个样吗 我的显示不全

**Comment by xfirefly** [comment]
> ![批注 2020-02-03 232401](https://user-images.githubusercontent.com/27768847/73665585-4e61c080-46dc-11ea-88f1-98a4f0619f09.png)
> 是这个样吗 我的显示不全

按 f 全屏

**Comment by xfirefly** [comment]
## 运行依赖
- Airplay 需要调用Apple Bonjour 广播服务, 安装zip包内的 Bonjour64.msi 或 Bonjour.msi
- 如安装后运行提示找不到 dll, 安装VC运行库 : https://aka.ms/vs/16/release/vc_redist.x86.exe

## Q & A
0. 视频投屏怎么用?
- 需要安装 [PotPlayer](https://daumpotplayer.com/download/) 或者 [VLC](https://www.videolan.org/vlc/) , 安装到C盘即可, 程序会调用其播放视频
1. 按 f 全屏后图像显示不全 ?   
-  修改 win10/设置/显示/缩放与布局 为 100%,  因请求iOS/Mac端编码1080p视频, 所以显示器最低要求为1920*1080
2. 连接黑屏 ?  
- 确认是不是防火墙禁止了exe联网
3. 杀毒软件报毒 ?
- 因程序加壳, 360或者Win杀毒会误报, 担心的话请禁止程序连互联网
4. iPhone找不到设备 win-airplay ?
- 确认安装了Apple Bonjour 服务
