### ISSUE TITLE
可以mirror但是airplay选中后potplayer卡在“即将播放”状态

### ISSUE THREAD

**Issue by markringo** [xfirefly/Airplay-SDK#84]
iPhone11Pro，iOS15.1,   PotPlayer 2109
防火墙均已设置正常
用系统镜像正常
但是airplay自动调出Potplayer但无法播放
Potplayer会卡在“即将播放”字样提示

但是系统自带相册里的视频可以正常airplay（一个无边框的窗口）似乎不是使用Potplayer

**Comment by xfirefly** [comment]
Potplayer  不支持播放有些app 传过来的url
