### ISSUE TITLE
youku投屏至windows，应用崩溃

### ISSUE THREAD

**Issue by prosup** [xfirefly/Airplay-SDK#9]
直接退了，没有任何提示信息

**Comment by xfirefly** [comment]
目前只做了屏幕镜像,  投youku 时是进入了投视频模式, 后续打算接 vlc 来播放视频

**Comment by xfirefly** [comment]
## 运行依赖
- Airplay 需要调用Apple Bonjour 广播服务, 安装zip包内的 Bonjour64.msi 或 Bonjour.msi
- 如安装后运行提示找不到 dll, 安装VC运行库 : https://aka.ms/vs/16/release/vc_redist.x86.exe

## Q & A
0. 视频投屏怎么用?
- 需要安装 [PotPlayer](https://daumpotplayer.com/download/) 或者 [VLC](https://www.videolan.org/vlc/) , 安装到C盘即可, 程序会调用其播放视频
1. 按 f 全屏后图像显示不全 ?   
-  修改 win10/设置/显示/缩放与布局 为 100%,  因请求iOS/Mac端编码1080p视频, 所以显示器最低要求为1920*1080
2. 连接黑屏 ?  
- 确认是不是防火墙禁止了exe联网
3. 杀毒软件报毒 ?
- 因程序加壳, 360或者Win杀毒会误报, 担心的话请禁止程序连互联网
4. iPhone找不到设备 win-airplay ?
- 确认安装了Apple Bonjour 服务
