### ISSUE TITLE
索尼x91j airplay投屏卡顿掉帧延迟高

### ISSUE THREAD

**Issue by Qishierhao** [xfirefly/Airplay-SDK#90]
iphone13 mini
系统版本：15.4.1

SONY 55X91J
系统版本：BRAVIA_VH2_M_CN-USER 10 QTG3.200305.006.S118656601 release-keys

**Comment by mofhu** [comment]
类似问题 SONY 65X91J，多个airplay 设备(iphone X / ipad pro 2020)，除卡顿外，还发现播放视频时，声音相对视频有延迟(0.5-1 s)

正在尝试优化网速，看是否能缓解。@xfirefly 请问电视和路由器间改用有线连接(目前是5G频段 距离50 cm)，是否有可能优化此问题？
