### ISSUE TITLE
使用后生成新文件夹

### ISSUE THREAD

**Issue by laozhuv** [xfirefly/Airplay-SDK#91]
每次使用完都会生成新文件夹，像下图这样，而且删除之后下次使用仍会生成。[https://m.360buyimg.com/babel/jfs/t1/51097/24/20781/21417/62d7ccb6E953c0231/8f1c3a461d5ee88d.jpg](url)

**Comment by xfirefly** [comment]
ui 库的缓存文件, 以后有时间换掉
